import { useEffect, useState } from 'react'
import { deleteHistoryItem, getHistory, getHistoryItem } from '../services/api'

function HistoryPanel({ onView }) {
  const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [deleting, setDeleting] = useState(null); const [viewingId, setViewingId] = useState(null)
  async function load() { setLoading(true); setError(''); try { setItems(await getHistory()) } catch (err) { setError(err?.message || 'Analysis history could not be loaded.') } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  async function view(id) { setViewingId(id); setError(''); try { onView(await getHistoryItem(id)) } catch (err) { setError(err?.message || 'This saved analysis is no longer available.') } finally { setViewingId(null) } }
  async function remove(id) { if (!window.confirm('Delete this saved analysis?')) return; setDeleting(id); try { await deleteHistoryItem(id); setItems((current) => current.filter((item) => item.id !== id)) } catch (err) { setError(err?.message || 'The analysis could not be deleted.') } finally { setDeleting(null) } }
  if (loading) return <section className="history-panel"><p>Loading analysis history…</p></section>
  return <section className="history-panel" aria-labelledby="history-heading"><div className="section-heading"><p className="section-kicker">Local history</p><h2 id="history-heading">Analysis History</h2><p>Review your previous analyses and compare your progress over time.</p></div>{error && <p className="history-error">{error}</p>}{items.length > 1 && <div className="progress-card"><strong>Progress</strong><span>Previous match: {items[1].match_score}%</span><span>Latest match: {items[0].match_score}%</span><b>{items[0].match_score - items[1].match_score >= 0 ? '+' : ''}{items[0].match_score - items[1].match_score}% match change · {items[1].skill_gap_count - items[0].skill_gap_count} fewer skill gaps</b></div>}{items.length === 1 && <p className="history-empty">Complete another analysis to see your progress.</p>}{!items.length && <p className="history-empty">No analysis history yet.</p>}<div className="history-list">{items.map((item) => <article className="history-item" key={item.id}><div><h3>{item.target_role}</h3><p>Analyzed {new Date(item.created_at).toLocaleString()}</p></div><div className="history-metrics"><strong>{item.match_score}%</strong><span>{item.skill_gap_count} skill gaps · {item.matching_skill_count} matching skills</span></div><div><button className="secondary-button" disabled={viewingId !== null || deleting !== null} onClick={() => view(item.id)}>{viewingId === item.id ? 'Loading…' : 'View Analysis'}</button><button className="text-button danger-text" disabled={viewingId !== null || deleting !== null} onClick={() => remove(item.id)}>{deleting === item.id ? 'Deleting…' : 'Delete'}</button></div></article>)}</div></section>
}
export default HistoryPanel
