import { useRef, useState } from 'react'
function formatFileSize(bytes) { return `${(bytes / (1024 * 1024)).toFixed(bytes < 1024 * 1024 ? 1 : 0)} MB` }
function ResumeUploader({ file, error, disabled, onChooseFile, onRemove }) {
  const inputRef = useRef(null)
  const [isDragging, setIsDragging] = useState(false)
  function handleDrop(event) { event.preventDefault(); setIsDragging(false); if (!disabled) onChooseFile(event.dataTransfer.files?.[0]) }
  return <section className="workspace-card" aria-labelledby="resume-upload-heading"><div className="card-heading"><span className="card-icon" aria-hidden="true">↥</span><div><h3 id="resume-upload-heading">Upload your resume</h3><p>Upload your PDF resume and let AI analyze your experience and skills.</p></div></div>{!file ? <div className={`dropzone ${isDragging ? 'is-dragging' : ''} ${error ? 'has-error' : ''}`} onDragEnter={(event) => { event.preventDefault(); setIsDragging(true) }} onDragOver={(event) => event.preventDefault()} onDragLeave={() => setIsDragging(false)} onDrop={handleDrop}><span className="upload-icon" aria-hidden="true">↑</span><strong>Drop your resume here</strong><span>or <button type="button" className="text-button" onClick={() => inputRef.current?.click()} disabled={disabled}>browse files</button></span><small>PDF files only · up to 10 MB</small></div> : <div className="file-selected"><span className="pdf-icon" aria-hidden="true">PDF</span><div className="file-details"><strong>{file.name}</strong><span>{formatFileSize(file.size)} · Ready to analyze</span></div><span className="file-check" aria-label="File selected">✓</span><div className="file-actions"><button type="button" className="text-button" onClick={() => inputRef.current?.click()} disabled={disabled}>Replace</button><button type="button" className="text-button danger-text" onClick={onRemove} disabled={disabled}>Remove</button></div></div>}<input ref={inputRef} className="visually-hidden" type="file" accept="application/pdf,.pdf" aria-label="Choose a PDF resume" disabled={disabled} onChange={(event) => { onChooseFile(event.target.files?.[0]); event.target.value = '' }} />{error && <p className="field-error" role="alert">{error}</p>}</section>
}
export default ResumeUploader
